export const EDIT_CONFIG  = {
	"layout":
		{
			"legend": "partner experience",
			"statementId": "partner",
			"primaryKeyName": "experienceId",
			"parentKeyName": "",
			"partitionKeyName": "",
			"controls": [
				{
					"code": "experienceId",
					"field": "experienceId",
					"label": "experienceId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "typeId",
					"field": "typeId",
					"label": "typeId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "partnerId",
					"field": "partnerId",
					"label": "partnerId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "organizationId",
					"field": "organizationId",
					"label": "organizationId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "organizationTypeId",
					"field": "organizationTypeId",
					"label": "organizationTypeId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "organizationSizeId",
					"field": "organizationSizeId",
					"label": "organizationSizeId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "companyName",
					"field": "companyName",
					"label": "companyName",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "occupationId",
					"field": "occupationId",
					"label": "occupationId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "positionId",
					"field": "positionId",
					"label": "positionId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "reasonId",
					"field": "reasonId",
					"label": "reasonId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "jobTitle",
					"field": "jobTitle",
					"label": "jobTitle",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "totalIncome",
					"field": "totalIncome",
					"label": "totalIncome",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "baseIncome",
					"field": "baseIncome",
					"label": "baseIncome",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "insurance",
					"field": "insurance",
					"label": "insurance",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "startDate",
					"field": "startDate",
					"label": "startDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "endDate",
					"field": "endDate",
					"label": "endDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "description",
					"field": "description",
					"label": "description",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "status",
					"field": "status",
					"label": "status",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "deleted",
					"field": "deleted",
					"label": "deleted",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "syncDate",
					"field": "syncDate",
					"label": "syncDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				}
			],
		}
};
