export const EDIT_CONFIG  = {
	layout:
		{
			legend: 'partner',
			statementId: 'textual',
			primaryKeyName: 'partnerId',
			parentKeyName: 'parentId',
			partitionKeyName: '',
			controls: [
				{
					code: 'partnerId',
					field: 'partnerId',
					label: 'partnerId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'lru',
					field: 'lru',
					label: 'lru',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'typeId',
					field: 'typeId',
					label: 'typeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'departmentTypeId',
					field: 'departmentTypeId',
					label: 'departmentTypeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'code',
					field: 'code',
					label: 'code',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'name',
					field: 'name',
					label: 'name',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'tradeName',
					field: 'tradeName',
					label: 'tradeName',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'nickName',
					field: 'nickName',
					label: 'nickName',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'homeland',
					field: 'homeland',
					label: 'homeland',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'portraitId',
					field: 'portraitId',
					label: 'portraitId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'gender',
					field: 'gender',
					label: 'gender',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'marital',
					field: 'marital',
					label: 'marital',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'birthday',
					field: 'birthday',
					label: 'birthday',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'individual',
					field: 'individual',
					label: 'individual',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'organizationId',
					field: 'organizationId',
					label: 'organizationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'scaleTypeId',
					field: 'scaleTypeId',
					label: 'scaleTypeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'industryId',
					field: 'industryId',
					label: 'industryId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'jobTitle',
					field: 'jobTitle',
					label: 'jobTitle',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'erpCode',
					field: 'erpCode',
					label: 'erpCode',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'contractNo',
					field: 'contractNo',
					label: 'contractNo',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'contractDate',
					field: 'contractDate',
					label: 'contractDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'bankId',
					field: 'bankId',
					label: 'bankId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'bankOffice',
					field: 'bankOffice',
					label: 'bankOffice',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'bankAccount',
					field: 'bankAccount',
					label: 'bankAccount',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'taxId',
					field: 'taxId',
					label: 'taxId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'nationalId',
					field: 'nationalId',
					label: 'nationalId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'religionId',
					field: 'religionId',
					label: 'religionId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'educationId',
					field: 'educationId',
					label: 'educationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'occupationId',
					field: 'occupationId',
					label: 'occupationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'positionId',
					field: 'positionId',
					label: 'positionId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'loginUserId',
					field: 'loginUserId',
					label: 'loginUserId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'emailId',
					field: 'emailId',
					label: 'emailId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'phonebookId',
					field: 'phonebookId',
					label: 'phonebookId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'contactId',
					field: 'contactId',
					label: 'contactId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'billingId',
					field: 'billingId',
					label: 'billingId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'residentId',
					field: 'residentId',
					label: 'residentId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'populationId',
					field: 'populationId',
					label: 'populationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'coverImage',
					field: 'coverImage',
					label: 'coverImage',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'coverImageFileEntryId',
					field: 'coverImageFileEntryId',
					label: 'coverImageFileEntryId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'coverImageId',
					field: 'coverImageId',
					label: 'coverImageId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'coverImageURL',
					field: 'coverImageURL',
					label: 'coverImageURL',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'smallImage',
					field: 'smallImage',
					label: 'smallImage',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'smallImageFileEntryId',
					field: 'smallImageFileEntryId',
					label: 'smallImageFileEntryId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'smallImageId',
					field: 'smallImageId',
					label: 'smallImageId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'smallImageURL',
					field: 'smallImageURL',
					label: 'smallImageURL',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'startDate',
					field: 'startDate',
					label: 'startDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'endDate',
					field: 'endDate',
					label: 'endDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'publishDate',
					field: 'publishDate',
					label: 'publishDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'expireDate',
					field: 'expireDate',
					label: 'expireDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'termDate',
					field: 'termDate',
					label: 'termDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'activeDate',
					field: 'activeDate',
					label: 'activeDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'extendDate',
					field: 'extendDate',
					label: 'extendDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'cancelDate',
					field: 'cancelDate',
					label: 'cancelDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'description',
					field: 'description',
					label: 'description',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'status',
					field: 'status',
					label: 'status',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'deleted',
					field: 'deleted',
					label: 'deleted',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'syncDate',
					field: 'syncDate',
					label: 'syncDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'phonebooks',
					field: 'phonebooks',
					label: 'phonebooks',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'emails',
					field: 'emails',
					label: 'emails',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'addresses',
					field: 'addresses',
					label: 'addresses',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'banks',
					field: 'banks',
					label: 'banks',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'experiences',
					field: 'experiences',
					label: 'experiences',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'educations',
					field: 'educations',
					label: 'educations',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'relations',
					field: 'relations',
					label: 'relations',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'licenses',
					field: 'licenses',
					label: 'licenses',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'hobbies',
					field: 'hobbies',
					label: 'hobbies',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				}
			],
		}
};
