export const EDIT_CONFIG  = {
	layout:
		{
			legend: 'contact phone',
			statementId: 'class_name',
			primaryKeyName: 'contactId',
			parentKeyName: '',
			partitionKeyName: '',
			controls: [
				{
					code: 'contactId',
					field: 'contactId',
					label: 'contactId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'resourceName',
					field: 'resourceName',
					label: 'resourceName',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'resourceId',
					field: 'resourceId',
					label: 'resourceId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'typeId',
					field: 'typeId',
					label: 'typeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'countryId',
					field: 'countryId',
					label: 'countryId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'phoneNumber',
					field: 'phoneNumber',
					label: 'phoneNumber',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'extension',
					field: 'extension',
					label: 'extension',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'mailing',
					field: 'mailing',
					label: 'mailing',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'main',
					field: 'main',
					label: 'main',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'verified',
					field: 'verified',
					label: 'verified',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'description',
					field: 'description',
					label: 'description',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'status',
					field: 'status',
					label: 'status',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'deleted',
					field: 'deleted',
					label: 'deleted',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'syncDate',
					field: 'syncDate',
					label: 'syncDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				}
			],
		}
};
