export const EDIT_CONFIG  = {
	layout:
		{
			legend: 'partner education',
			statementId: 'partner',
			primaryKeyName: 'educateId',
			parentKeyName: '',
			partitionKeyName: '',
			controls: [
				{
					code: 'educateId',
					field: 'educateId',
					label: 'educateId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'typeId',
					field: 'typeId',
					label: 'typeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'partnerId',
					field: 'partnerId',
					label: 'partnerId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'educationId',
					field: 'educationId',
					label: 'educationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'occupationId',
					field: 'occupationId',
					label: 'occupationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'graduateId',
					field: 'graduateId',
					label: 'graduateId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'graduateNo',
					field: 'graduateNo',
					label: 'graduateNo',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'graduateDate',
					field: 'graduateDate',
					label: 'graduateDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'graduateScore',
					field: 'graduateScore',
					label: 'graduateScore',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'eduOrganizationId',
					field: 'eduOrganizationId',
					label: 'eduOrganizationId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'eduName',
					field: 'eduName',
					label: 'eduName',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'startDate',
					field: 'startDate',
					label: 'startDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'endDate',
					field: 'endDate',
					label: 'endDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'issueDate',
					field: 'issueDate',
					label: 'issueDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'expireDate',
					field: 'expireDate',
					label: 'expireDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'description',
					field: 'description',
					label: 'description',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'status',
					field: 'status',
					label: 'status',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'deleted',
					field: 'deleted',
					label: 'deleted',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'syncDate',
					field: 'syncDate',
					label: 'syncDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				}
			],
		}
};
