export const EDIT_CONFIG  = {
	"layout":
		{
			"legend": "workspace attachment",
			"statementId": "",
			"primaryKeyName": "attachId",
			"parentKeyName": "",
			"partitionKeyName": "",
			"controls": [
				{
					"code": "attachId",
					"field": "attachId",
					"label": "attachId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "typeId",
					"field": "typeId",
					"label": "typeId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "workspaceId",
					"field": "workspaceId",
					"label": "workspaceId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "fileEntryId",
					"field": "fileEntryId",
					"label": "fileEntryId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "fileEntryTypeId",
					"field": "fileEntryTypeId",
					"label": "fileEntryTypeId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "title",
					"field": "title",
					"label": "title",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "issueNo",
					"field": "issueNo",
					"label": "issueNo",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "issueDate",
					"field": "issueDate",
					"label": "issueDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "expireDate",
					"field": "expireDate",
					"label": "expireDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "issueOrgId",
					"field": "issueOrgId",
					"label": "issueOrgId",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "issuer",
					"field": "issuer",
					"label": "issuer",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "content",
					"field": "content",
					"label": "content",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "description",
					"field": "description",
					"label": "description",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "status",
					"field": "status",
					"label": "status",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "deleted",
					"field": "deleted",
					"label": "deleted",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "syncDate",
					"field": "syncDate",
					"label": "syncDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				}
			],
		}
};
