export const EDIT_CONFIG  = {
	"layout":
		{
			"legend": "domain",
			"statementId": "textual",
			"primaryKeyName": "domainId",
			"parentKeyName": "parentId",
			"partitionKeyName": "",
			"controls": [
				{
					"code": "lru",
					"field": "lru",
					"label": "lru",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "type",
					"field": "type",
					"label": "type",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "code",
					"field": "code",
					"label": "code",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "name",
					"field": "name",
					"label": "name",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "priority",
					"field": "priority",
					"label": "priority",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "main",
					"field": "main",
					"label": "main",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "hidden",
					"field": "hidden",
					"label": "hidden",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "multiple",
					"field": "multiple",
					"label": "multiple",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "settings",
					"field": "settings",
					"label": "settings",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "startDate",
					"field": "startDate",
					"label": "startDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "endDate",
					"field": "endDate",
					"label": "endDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "publishDate",
					"field": "publishDate",
					"label": "publishDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "expireDate",
					"field": "expireDate",
					"label": "expireDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "description",
					"field": "description",
					"label": "description",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "status",
					"field": "status",
					"label": "status",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "deleted",
					"field": "deleted",
					"label": "deleted",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": false,
					"initValue": null,
					"inputValue": null,
					"options": null
				},
				{
					"code": "syncDate",
					"field": "syncDate",
					"label": "syncDate",
					"visible": true,
					"initialise": true,
					"placeholder": "",
					"datetime": true,
					"initValue": null,
					"inputValue": null,
					"options": null
				}
			],
		}
};
