export const EDIT_CONFIG  = {
	layout:
		{
			legend: 'workspace',
			statementId: '',
			primaryKeyName: 'workspaceId',
			parentKeyName: 'parentId',
			partitionKeyName: '',
			controls: [
				{
					code: 'workspaceId',
					field: 'workspaceId',
					label: 'workspaceId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'typeId',
					field: 'typeId',
					label: 'typeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'lru',
					field: 'lru',
					label: 'lru',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'code',
					field: 'code',
					label: 'code',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'name',
					field: 'name',
					label: 'name',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'inviteType',
					field: 'inviteType',
					label: 'inviteType',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'confirmType',
					field: 'confirmType',
					label: 'confirmType',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'resourceName',
					field: 'resourceName',
					label: 'resourceName',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'resourceId',
					field: 'resourceId',
					label: 'resourceId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'creatorId',
					field: 'creatorId',
					label: 'creatorId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'folderId',
					field: 'folderId',
					label: 'folderId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'fileEntryId',
					field: 'fileEntryId',
					label: 'fileEntryId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'fileEntryTypeId',
					field: 'fileEntryTypeId',
					label: 'fileEntryTypeId',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'wiki',
					field: 'wiki',
					label: 'wiki',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'gallery',
					field: 'gallery',
					label: 'gallery',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'conversation',
					field: 'conversation',
					label: 'conversation',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'chat',
					field: 'chat',
					label: 'chat',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'calendar',
					field: 'calendar',
					label: 'calendar',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'task',
					field: 'task',
					label: 'task',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'search',
					field: 'search',
					label: 'search',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'drive',
					field: 'drive',
					label: 'drive',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'visible',
					field: 'visible',
					label: 'visible',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'opened',
					field: 'opened',
					label: 'opened',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'archived',
					field: 'archived',
					label: 'archived',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'project',
					field: 'project',
					label: 'project',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'startDate',
					field: 'startDate',
					label: 'startDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'endDate',
					field: 'endDate',
					label: 'endDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'description',
					field: 'description',
					label: 'description',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'status',
					field: 'status',
					label: 'status',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'deleted',
					field: 'deleted',
					label: 'deleted',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'syncDate',
					field: 'syncDate',
					label: 'syncDate',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: true,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'moderator',
					field: 'moderator',
					label: 'moderator',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'worker',
					field: 'worker',
					label: 'worker',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'monitor',
					field: 'monitor',
					label: 'monitor',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'approver',
					field: 'approver',
					label: 'approver',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'attachments',
					field: 'attachments',
					label: 'attachments',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'comments',
					field: 'comments',
					label: 'comments',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				},
				{
					code: 'approval',
					field: 'approval',
					label: 'approval',
					visible: true,
					initialise: true,
					placeholder: '',
					datetime: false,
					initValue: null,
					inputValue: null,
					options: null
				}
			],
		}
};
